-- ============================================================================
-- Merge rows that are the same part into one row per board.
--
-- Rule: same component + value + package = one row, one stock figure, one set of
-- Inward/Outward/Return. Part number is not part of the identity — the same part
-- bought from two suppliers, or a line where nobody filled the part number in,
-- is still the same physical part.
--
-- Three groups exist today, all with ZERO transactions, which is why this is
-- safe to run now. Each is written out explicitly rather than generated by a
-- loop: this deletes rows, so every statement should be readable on its own.
--
--   RS485 · Main Board  Resistor 1K R0402
--     keep #16 R4 (4,500, part C106235)   +   #17 R38 (0, no part)
--   RS485 · Main Board  Connectors 2 PIN JST · JST-XH 1X2 STREIGHT
--     keep #52 RTD (0)                    +   #57 BAT-IN (1,415)
--   LORA  · Main Board  Capacitor 100nF C0402
--     keep #4 C2,C8 (0, note NC)          +   #5 C9..C32 (3,910, part C60474)
--
-- The lowest serial survives so the part keeps its position in the BOM, and
-- takes on the merged quantity, both sets of designators, and whichever part
-- number was filled in. LORA #4's "NC" note is dropped because the merged row
-- holds 3,910 — "not counted" stops being true of it.
--
-- Transactions are repointed before any delete, so this stays correct even if
-- it is run later, once stock has started moving.
--
-- Idempotent: each step is guarded on the duplicate still existing, so running
-- it twice does nothing the second time.
-- Run in Supabase: SQL Editor -> paste -> Run.
-- ============================================================================


-- ---------------------------------------------------------------------------
-- 1. RS485 · Main Board — Resistor 1K R0402 — R4 + R38
-- ---------------------------------------------------------------------------
do $$
declare keep_id uuid; drop_id uuid; qty numeric;
begin
  select id into keep_id from public.bom_rs485_components
   where sub_board = 'Main Board' and component = 'Resistor' and value = '1K'
     and package = 'R0402' and label = 'R4';
  select id, opening_quantity into drop_id, qty from public.bom_rs485_components
   where sub_board = 'Main Board' and component = 'Resistor' and value = '1K'
     and package = 'R0402' and label = 'R38';

  if keep_id is not null and drop_id is not null then
    update public.bom_rs485_transactions set component_id = keep_id where component_id = drop_id;
    update public.bom_rs485_components
       set opening_quantity = opening_quantity + qty,
           label            = 'R4,R38',
           quantity_note    = case when opening_quantity + qty > 0 then null else quantity_note end
     where id = keep_id;
    delete from public.bom_rs485_components where id = drop_id;
    raise notice 'merged RS485 Resistor 1K R0402 (R4 + R38)';
  end if;
end $$;


-- ---------------------------------------------------------------------------
-- 2. RS485 · Main Board — Connectors 2 PIN JST — RTD + BAT-IN
-- ---------------------------------------------------------------------------
do $$
declare keep_id uuid; drop_id uuid; qty numeric;
begin
  select id into keep_id from public.bom_rs485_components
   where sub_board = 'Main Board' and component = 'Connectors' and value = '2 PIN JST'
     and package = 'JST-XH 1X2 STREIGHT' and label = 'RTD';
  select id, opening_quantity into drop_id, qty from public.bom_rs485_components
   where sub_board = 'Main Board' and component = 'Connectors' and value = '2 PIN JST'
     and package = 'JST-XH 1X2 STREIGHT' and label = 'BAT-IN';

  if keep_id is not null and drop_id is not null then
    update public.bom_rs485_transactions set component_id = keep_id where component_id = drop_id;
    update public.bom_rs485_components
       set opening_quantity = opening_quantity + qty,
           label            = 'RTD,BAT-IN',
           quantity_note    = case when opening_quantity + qty > 0 then null else quantity_note end
     where id = keep_id;
    delete from public.bom_rs485_components where id = drop_id;
    raise notice 'merged RS485 Connectors 2 PIN JST (RTD + BAT-IN)';
  end if;
end $$;


-- ---------------------------------------------------------------------------
-- 3. LORA · Main Board — Capacitor 100nF C0402 — C2,C8 + C9..C32
-- ---------------------------------------------------------------------------
do $$
declare keep_id uuid; drop_id uuid; qty numeric; part text;
begin
  select id into keep_id from public.bom_lora_components
   where sub_board = 'Main Board' and component = 'Capacitor' and value = '100nF'
     and package = 'C0402' and label = 'C2,C8';
  select id, opening_quantity, part_number into drop_id, qty, part
    from public.bom_lora_components
   where sub_board = 'Main Board' and component = 'Capacitor' and value = '100nF'
     and package = 'C0402' and label = 'C9,C10,C15,C18,C20,C22,C31,C32';

  if keep_id is not null and drop_id is not null then
    update public.bom_lora_transactions set component_id = keep_id where component_id = drop_id;
    update public.bom_lora_components
       set opening_quantity = opening_quantity + qty,
           label            = 'C2,C8,C9,C10,C15,C18,C20,C22,C31,C32',
           part_number      = coalesce(part_number, part),
           quantity_note    = case when opening_quantity + qty > 0 then null else quantity_note end
     where id = keep_id;
    delete from public.bom_lora_components where id = drop_id;
    raise notice 'merged LORA Capacitor 100nF C0402 (C2,C8 + C9..C32)';
  end if;
end $$;


-- ---------------------------------------------------------------------------
-- 4. Close the serial gaps the deletions leave, following display order.
-- ---------------------------------------------------------------------------
with renum as (
  select id, row_number() over (partition by sub_board order by sort_order, s_no, created_at) as n
  from public.bom_rs485_components
)
update public.bom_rs485_components c
   set s_no = r.n, s_no_raw = r.n::text
  from renum r
 where r.id = c.id and c.s_no is distinct from r.n;

with renum as (
  select id, row_number() over (partition by sub_board order by sort_order, s_no, created_at) as n
  from public.bom_lora_components
)
update public.bom_lora_components c
   set s_no = r.n, s_no_raw = r.n::text
  from renum r
 where r.id = c.id and c.s_no is distinct from r.n;


-- ---------------------------------------------------------------------------
-- 5. VERIFY — expect RS485 Main 57, LORA Main 51, numbered = rows, gaps 0.
-- ---------------------------------------------------------------------------
select '4G' as device, sub_board, count(*) as rows, count(s_no) as numbered,
       max(s_no) - count(s_no) as gap_or_dupe
from public.bom_4g_components group by sub_board
union all
select 'RS485', sub_board, count(*), count(s_no), max(s_no) - count(s_no)
from public.bom_rs485_components group by sub_board
union all
select 'LORA', sub_board, count(*), count(s_no), max(s_no) - count(s_no)
from public.bom_lora_components group by sub_board
order by device, sub_board;
